### ISSUE TITLE
https://etcher.io/

### ISSUE THREAD

**Issue by necrose99** [sakaki-/gentoo-on-rpi3-64bit#11]
***TIPS 
 (for Windows 10 the YE olden Win32 disk imager may/may not work dep on build of w10) 
https://github.com/pbatard/rufus/issues  (7zip , then use Rufus on windows )

* Etcher , Windows or Linux ETC.   feed tarball+DD in one step. no need to untar  

https://resin.io , can run on multiple pi's with SAKAKI as a docker image ie Docker clustering (docker+cluster very stripped down image..) 
or soon via gentoo and multi-arch alpine linux ,  https://github.com/gentoo/gentoo-docker-images 
build on any garden variety desktop.  on in the cloud.  keep packages... etc..

My use case is for PENTOO Linux   (layman -a pentoo ) etc.
, and or having an ISO for say a SOFTIORN ,  server or 
(workstation.-dev-box 500 ish) 
http://www.penguincomputing.com/products/rackmount-servers/valkre-servers/ (Cavium ThunderX family)
and cloud security reserch , so this will be a nice first step... for arm64

anyhow I'll build for pentoo on sakaki- gentoo , can share via dropbox back...

**Comment by sakaki-** [comment]
Thanks, tried Etcher and it works well, now recommending it as the default non-Linux-CLI install method.
