### ISSUE TITLE
extra goodies

### ISSUE THREAD

**Issue by necrose99** [sakaki-/gentoo-on-rpi3-64bit#12]
https://plus.google.com/communities/111215969224831918857

https://www.dropbox.com/sh/4u9gbhps0ek402e/AAC5VLBE32cwH2gGjkj0Yz9sa?dl=0

note some the sabayon packages work-ish but kinda not...  equo/entropy/molecule..... 
Zenmap gui dose work...  requires hacking ebuild keywords .... to use ~arm64 ... and repoman.... 
golang , etc... 
hopefully can get docker packages to build..... so you can cluster more easily with other pi's... 

Jenkins .... might be nice to test.....  , for obvious reasons , can automate a few emerges..... 
slowly adding a few pkgs form [@pentoo](https://github.com/pentoo/pentoo-overlay) 
as a meddlesome Security Engineer , this platform could be quite useful..

**Comment by necrose99** [comment]
anyhow I've uploaded to dropbox , can be tested. ...  (I need to get me a server .....) but for now 
enjoy ... packages we built on the pi3....

**Comment by necrose99** [comment]
[Packages.txt](https://github.com/sakaki-/gentoo-on-rpi3-64bit/files/2194511/Packages.txt)

https://www.dropbox.com/s/1r3dnawxc46lzq6/packages_7-8-2018.tar.xz?dl=0  

few days out of sync but much of KDE however might need a pine/rock64 with 4-GIGs of ram .

**Comment by viking76** [comment]
i have worked to compile nodejs with no success on -arm64, who have a success with this ebuild ?

**Comment by necrose99** [comment]
https://www.dropbox.com/preview/sakaki--gentoo-on-rpi3-64bit/packages-rpi3-arm64/net-libs/nodejs/nodejs-8.11.2-1.xpak?role=personal

**Comment by viking76** [comment]
no access

**Comment by necrose99** [comment]
https://discord.gg/5yhY9bg  jump into pentoo Linux room.

**Comment by necrose99** [comment]
[nodejs-8.11.2.tbz2.zip](https://github.com/sakaki-/gentoo-on-rpi3-64bit/files/2271956/nodejs-8.11.2.tbz2.zip)

**Comment by sakaki-** [comment]
Old issue, closing now in pre 1.5.0 housecleaning
