### ISSUE TITLE
minor tweek to wiki , 

### ISSUE THREAD

**Issue by necrose99** [sakaki-/gentoo-on-rpi3-64bit#23]
crossdev -t aarch64-unknown-linux-gnu --stable --init-target -oO /usr/local/portage-crossdev

ensures packages get put in the overlay as per wiki documentation... 
as crosdev will shove it almost anyplace...  , makes fails easier to fix or add a package ie Pypy3 wich needs >2gigs to compile and will die 2/3 the way compiled on rpi3 

https://github.com/olsonbg/crossdev-gentoo 

Initialize new environment

Setup in new toolchain environment(s) with:

crossdev -t x86_64-pc-mingw32 --stable --init-target -oO /usr/local/portage/crossdev
crossdev -t i686-pc-mingw32 --stable --init-target -oO /usr/local/portage/crossdev

**Comment by sakaki-** [comment]
Finally got round to this ([commit](https://github.com/sakaki-/gentoo-on-rpi3-64bit/wiki/Set-Up-Your-Gentoo-PC-for-Cross-Compilation-with-crossdev/_compare/dc69f08cf847b8a344cda046e945d2f7ad5fac15...b36bb82eaaa4b8570d69c0c67fc531381dca4119)) - apologies for leaving it open so long ><
Closing
