### ISSUE TITLE
Overwork kernel

### ISSUE THREAD

**Issue by V10lator** [sakaki-/gentoo-on-rpi3-64bit#30]
The kernel really needs to change: I'm currently able to use less hardware than on the kernel from the rpi foundation! If you need help with that just tell me how you build the kernel / where to find the sources and I'll do my best to make a new config.

**Comment by sakaki-** [comment]
The kernel is based on the official (i.e. from the rpi foundation) `bcmrpi3_defconfig` kernel (see [this link](https://github.com/sakaki-/bcmrpi3-kernel)), for maximum compatibility with upstream. Instructions are provided in the readme for building your own; and as a user of Gentoo, you no doubt can easily do so ^-^
Closing.
