### ISSUE TITLE
sys-libs/glibc build with debugging kills the system

### ISSUE THREAD

**Issue by V10lator** [sakaki-/gentoo-on-rpi3-64bit#31]
I need glibc build with

```
CFLAGS="${CFLAGS} -ggdb"
CXXFLAGS="${CXXFLAGS} -ggdb"
FEATURES="${FEATURES} splitdebug compressdebug"
```

for debugging purposes. Sadly the system crashes while installing the newly compiled glibc (seems to be this bug triggered by systemd which turns into the init system being killed and as such a full system crash: https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1558120 ) and won't boot anymore untill your binary package of glibc has been restored.

**Comment by sakaki-** [comment]
I suggest you post about this to the [Gentoo on ARM](https://forums.gentoo.org/viewforum-f-62.html) forum. As the currently-shipped system is OpenRC-based, I won't be able to track down a systemd-related problem until I have the 17.0 profile / full `pie` rebuild done (which I am working on now). Someone on the forum (such as NeddySeagoon) may be better able to help you sort this one out than I can.
