### ISSUE TITLE
Desktop extends past display

### ISSUE THREAD

**Issue by teyter** [sakaki-/gentoo-on-rpi3-64bit#36]
Its like it doesnt fit the screen. The menu bar and launch bar are out of view, only partially visible. Display settings in xfce do not offer solution

**Comment by sakaki-** [comment]
What type of display are you using? You may need to edit `/boot/config.txt`: try in the first instance commenting out the line `disable_overscan=1` (and then rebooting).

**Comment by teyter** [comment]
That worked! Many thanks!
