### ISSUE TITLE
verifying image on window

### ISSUE THREAD

**Issue by AcemiPulco** [sakaki-/gentoo-on-rpi3-64bit#45]
Hello, good days. Sorry for that probably stupid question: I need to verify the image file using the signature on windows! So, I used gpg.exe (please see https://gpg4win.org/download.html) for that and I have following results:
..........
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\WINDOWS\system32>"C:\Program Files (x86)\GnuPG\bin\gpg.exe" --verify C:\Users\fyallur\Downlo
ads\Gentoo\genpi64.img.xz.asc C:\Users\fyallur\Downloads\Gentoo\genpi64.img.xz
gpg: Signature made 04/03/18 18:35:15 Turkey Standard Time
gpg:                using RSA key 4120B21484A776474658390931C80DB2DDE76CEA
gpg: Can't check signature: No public key
.........

So, couldn't decide if the result is OK or NOT

regards,

**Comment by sakaki-** [comment]
Hi, you need to import my public key from a keyserver, see e.g. [these notes](https://riseup.net/en/security/message-security/openpgp/gpg-keys#find-on-the-key-servers), for this to work.

Use <kbd>File</kbd> &rarr; <kbd>Lookup Certificates on Server...</kbd> and either enter the RSA key id (`4120B21484A776474658390931C80DB2DDE76CEA`) or my email address (sakaki@deciban.com) as search terms.

Once you have imported the key, you should be able to validate.

**Comment by AcemiPulco** [comment]
thanks
