### ISSUE TITLE
Refusing to create a cross-compiler using the same target name as your host utils.

### ISSUE THREAD

**Issue by IEXWER** [sakaki-/gentoo-on-rpi3-64bit#47]
I don't get a gentoo linux pc,so i try to compile a linux, follow the wiki, on a raspberry 3b with img from you art work.
but I met this.

pi64 /usr/local/portage-crossdev/metadata # crossdev --stable -t aarch64-unknown-linux-gnu --genv 'USE="cxx multilib fortran -mudflap nls openmp -sanitize"'    
 * Refusing to create a cross-compiler using the same
 * target name as your host utils.

And i want to know how to fix it.
If i made some wrong please tell me.

**Comment by IEXWER** [comment]
Ok,it seem to i have a aarch64-unknown-linux-gnu,

pi64 /usr/local/portage-crossdev/metadata # gcc-config -l
 [1] aarch64-unknown-linux-gnu-7.3.0

So i can't remake another.

**Comment by sakaki-** [comment]
Hi, closing this, as you don't need a cross-compiler when building natively, as you have just noted.
Please also see my response to your related issue #48.
Best, sakaki
