### ISSUE TITLE
GLSL ES 3.00

### ISSUE THREAD

**Issue by Bargest** [sakaki-/gentoo-on-rpi3-64bit#54]
Hello!

While booting qemu with "-device virtio-gpu-pci,virgl -display gtk,gl=on", I'm getting an error:
```
qemu_gl_create_compile_shader: compile vertex error
0:2(10) error: GLSL ES 3.00 is not supported. Supported versions are: 1.10, 1.20, and 1.00 ES
```
glxinfo | grep OpenGL output:
```
OpenGL vendor string: Broadcom
OpenGL renderer string: VC4 V3D 2.1
OpenGL version string: 2.1 Mesa 18.1.4
OpenGL shading language version string: 1.20
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 2.0 Mesa 18.1.4
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 1.0.16
OpenGL ES profile extensions:
```
This seems not to be enough. Of course I've disabled bindist for Mesa as it is suggested on forums, but it gave me nothing except some extra heat on my CPU while compiling.

Current mesa flags:
```
classic dri3 egl gallium gbm gles1 gles2 llvm nptl xa xvmc vc4
```

I was able to run a prebuilt qemu on openSUSE for rpi with virgl graphics, so it should be possible (but openSUSE has very old kernel and KVM support seems to be incomplete. Also I cannot rebuild qemu from source for openSUSE because the only working prebuild qemu uses odd custom constants for interaction with KVM and normal ones don't work, so I had to change linux distro).

Is there a way to update OpenGL ES in gentoo for rpi so qemu would be able to run?

**Comment by sakaki-** [comment]
Old issue, closing now in pre 1.5.0 housecleaning
Apologies for not getting back on this one - this is quite a specialized question, you may have better luck posting on the Gentoo forums. It isn't something I've had a chance to look at in any depth, unfortunately.

It is possible things have improved with the V3D support for the Pi4 in the forthcoming 1.5.0 release.

Best, sakaki
