### ISSUE TITLE
sys-process/at-3.1.20 and app-crypt/veracrypt-1.22

### ISSUE THREAD

**Issue by andi4567** [sakaki-/gentoo-on-rpi3-64bit#56]
Just want to report that I could successfully compile and run the at daemon and  veracrypt.

**Comment by sakaki-** [comment]
Added to the `package.accept_keywords` set in the [rpi3 overlay](https://github.com/sakaki-/rpi3-overlay/commit/4fa63df4d63b62accaffafd17a07f53e5d5f311e), thanks for reporting!
