### ISSUE TITLE
PGP Signature Key Missing

### ISSUE THREAD

**Issue by NoSuck** [sakaki-/gentoo-on-rpi3-64bit#60]
Thank you for sharing the work you've done.

http://pool.sks-keyservers.net/pks/lookup?search=DDE76CEA
https://pgp.mit.edu/pks/lookup?search=DDE76CEA

> No results found

Did I miss something?  I can't find the key mentioned in `README.md`.

**Comment by sakaki-** [comment]
I think you missed the 0x ^-^

Try:
```
https://pgp.mit.edu/pks/lookup?search=0xDDE76CEA
```
or
```
https://pgp.mit.edu/pks/lookup?search=sakaki@deciban.com
```
You don't need the prefix though to do:
```
gpg --recv-keys DDE76CEA
```
hth, S.

**Comment by NoSuck** [comment]
Wow, that is ridiculous.  Thank you!
