### ISSUE TITLE
5001 port is not open and unable to open it

### ISSUE THREAD

**Issue by manash-biswal** [sakaki-/gentoo-on-rpi3-64bit#64]
5001 port is not open and unable to open it
As we are planning to use iperf in UDP mode, the port 5001 needs to be open. Pleas help.

**Comment by sakaki-** [comment]
@manash-biswal,

as shipped, the image does not have any firewall rules active, so, unless you have set some yourself, no ports should be being blocked. Also, `iperf3` ships with the image. To run it on port 5001 (it defaults to 5201), issue e.g.:
```console
demouser@pi64 ~ $ sudo iperf3 --server --version4 --port 5001
```
You can check it is listening by running `netstat -vatn` in another terminal (the control connection is TCP, even for UDP tests). Now determine the IP address of your RPi3, using e.g. `ifconfig` in another terminal. Suppose it is e.g. `192.168.1.100`

Then, on a Linux PC on the same subnet, you can connect (assuming you have the `iperf3` software installed there too; or, just use another RPi3!):

```console
user@linuxpc ~ $ iperf3 --client 192.168.1.100 --port 5001 --udp
```

> Substitute the address you get from `ifconfig` for `192.168.1.100` in the above.

Just tried this locally and it seems to work OK here. You can of course daemonize the `iperf3` server, or run it as a service, once you know it is working.

hth, sakaki

**Comment by sakaki-** [comment]
Closing. Please feel free to re-open if my comments above did not address the issue for you.
Best, sakaki
