### ISSUE TITLE
Tabs

### ISSUE THREAD

**Issue by tdubz1** [sakaki-/gentoo-on-rpi3-64bit#70]
Not really an issue but for some reason my tabs have moved to the right of the screen instead of the left when my mouse went into a strange mode. I’ve fixed my mouse now however the tabs are still on the left. How do I fix this? Thanks TDubz

**Comment by tdubz1** [comment]
Desktop

**Comment by sakaki-** [comment]
Perhaps you have moved the transparent expandable separator in the panel layout (or added a second separator)? Left-click on the top panel (in a gray area with no button or other icon in it) and select <kbd>Panel</kbd>&rarr;<kbd>Panel Preferences...</kbd>. Then click on the <kbd>Items</kbd> tab. Where do you see the "Separator" item in the list?

**Comment by tdubz1** [comment]
Thank you, that has helped! It is now back to normal! (The seperator was at the top!)

**Comment by sakaki-** [comment]
Hi @tdubz1 - glad that helped ^-^
However, I see you've closed and then reopened the issue; are you still experiencing problems with this? Best, S.

**Comment by tdubz1** [comment]
No, sorry I didn’t mean to open the issue again. I will close the issue now. Thanks for your help.
