### ISSUE TITLE
Remote Desktop Win10 PC to Pi

### ISSUE THREAD

**Issue by tdubz1** [sakaki-/gentoo-on-rpi3-64bit#71]
How do I remote desktop from my Win10 PC to my Raspberry Pi running your Gentoo OS because I want to be able to control my Pi from my PC. I have searched for RDP programmes on the internet however haven't been successful,

Thanks,

 tdubz

**Comment by sakaki-** [comment]
Hi @tdubz1,

two options here. First, you could use VNC, per my wiki article [here](https://github.com/sakaki-/gentoo-on-rpi3-64bit/wiki/Run-a-Remote-VNC-Desktop-on-your-RPi3).

Second, if you really want RDP, this can be done too, as the xrdp and xorgxrdp ebuilds are in the overlay. To get them, issue:
```console
demouser@pi64 ~ $ sudo emaint sync --repo rpi3
demouser@pi64 ~ $ sudo emerge -av net-misc/xrdp net-misc/xorgxrdp
```

 Then edit the file /etc/xrdp/sesman.ini, and comment out the line near the top so it reads: 
```ini
#ListenAddress=127.0.0.1
```

Leave the rest of the file as-is, and save, exiting the editor. (This change instructs the server to listen on all interfaces for connections, not just localhost.)

Then issue: 
```console
demouser@pi64 ~ $ sudo rc-service xrdp start
demouser@pi64 ~ $ sudo rc-update add xrdp default
```

And you should have an RDP server running! If you find your PI's IP address you should then be able to connect to it via Windows Remote Desktop. Note that Windows will complain about certificate authentication - just accept the warning and continue anyway when prompted (you'd need to set this up properly for production use, obviously). You'll then get a login dialog (hopefully) - choose Xorg as the session type (the default) and enter your login credentials (e.g. demouser as username, raspberrypi64 as password, or whatever you have set). Note that you can't log in directly as root, for security.

**Comment by tdubz1** [comment]
Thank you very much, sakaki! It worked extremely well - I have been trying to figure it out for a long time! Your help is much appreciated,

tdubz

**Comment by tdubz1** [comment]
I will close the issue now.

**Comment by sakaki-** [comment]
Glad it worked out for you! Actually, this has reminded me I need to write up a wiki entry for the RDP option: I'll aim to do that within the next week or so.
Best, S.
