### ISSUE TITLE
Can't logon

### ISSUE THREAD

**Issue by tdubz1** [sakaki-/gentoo-on-rpi3-64bit#72]
When I booted up my Raspberry Pi 3B+ running your OS, It said I am in '(none)'! I don't go to the regular login screen and am met with terminal like page that I can't get out of,
This is urgent - I can't  access any of my files!

Please help me,

tdubz

**Comment by sakaki-** [comment]
Can you log in as demouser at the terminal prompt? Looks like your root filesystem may have become corrupted somehow; did your system suffer a hard powerdown or similar?

**Comment by tdubz1** [comment]
No, I can’t login as demouser because I deleted that account and made a new one but I can login to that one. Yes, I think it did suffer a hard powerdown (when I turned the power off to the Pi).

**Comment by sakaki-** [comment]
Can you log in as your new user at the terminal prompt? Or as root (the default password for root is raspberrypi64, unless you changed that too)?

**Comment by tdubz1** [comment]
Yes I can

**Comment by sakaki-** [comment]
OK, so logon as root, and run `findmnt`; what output do you get?

**Comment by tdubz1** [comment]
https://drive.google.com/file/d/1T7VRedXmiwIWpM47CCRecSw3sz9H-VZc/view?usp=sharing

**Comment by sakaki-** [comment]
OK so as expected your root partition is read only (first line of output, the `ro` tag).
Try running (as root)
```console
# e2fsck -f /dev/mmcblk0p2
```
Once it completes, try rebooting.
If `e2fsck` reports errors, you should **backup the card** before proceeding, and then reboot, run the command again, and answer y when prompted. Then try rebooting again, with luck your system will come up.

**Comment by tdubz1** [comment]
Thank you! I am now able to log in! 
I am very thankful and appreciate your time.
tdubz

**Comment by sakaki-** [comment]
OK - good news!
It's quite a common thing to happen on Linux, if your system suffers a hard poweroff rather than a clean shutdown.
I'll close this issue now.
Best,
sakaki
