### ISSUE TITLE
How do I enable the sqlite3 extension for my Pocketmine Server?

### ISSUE THREAD

**Issue by tdubz1** [sakaki-/gentoo-on-rpi3-64bit#78]
How do I enable the sqlite3 extension for my Pocketmine Server? I need it for a plugin however when I remove the semi-colon in the `php.ini` Pocketmine tells me there is some error with loading it,
Cheers,
tdubz

**Comment by sakaki-** [comment]
Could you please post the error message you get from `pocketmine`?
Thanks, sakaki

**Comment by tdubz1** [comment]
[https://drive.google.com/file/d/1S2_Iiv4_mAciD0sLieRSaJ3CawanmhSO/view](url)

**Comment by sakaki-** [comment]
You need to re-emerge the `dev-lang/php` package with the `sqlite` USE flag set. To do do, issue
```console
demouser@pi64 ~ $  echo "dev-lang/php sqlite" | sudo tee -a /etc/portage/package.use/php
```

then:
```console
demouser@pi64 ~ $  nice -n 19 sudo emerge --verbose --oneshot dev-lang/php
```

This may take some time to complete, so leave it to run overnight perhaps. Once done, if you restart your pocketmine server, you should (hopefully) find you can load the sqlite3 extension.

**Comment by tdubz1** [comment]
Thank you very much @sakaki- I am very thankful for your help,
The plugin I want to run is now running smoothly!
