### ISSUE TITLE
Support for BTRFS root

### ISSUE THREAD

**Issue by Necktwi** [sakaki-/gentoo-on-rpi3-64bit#85]
Please compile in `BTRFS` into the kernel.

**Comment by sakaki-** [comment]
If you submit an appropriate PR for [`bcmrpi3-kernel-bis`](https://github.com/sakaki-/bcmrpi3-kernel-bis) (see e.g. [this example](https://github.com/sakaki-/bcmrpi3-kernel-bis/pull/6)) I'll review and merge it.

**Comment by Necktwi** [comment]
Please update the image with the latest kernel. I shall modify it to `btrfs` root.

**Comment by sakaki-** [comment]
When the next release comes out it will have either the current, or a later release kernel included (so should have `btrfs` support). I'm in the early stages of working on this now, expected release is sometime near the end of June. Will keep this issue open as a reminder until then.
Best, sakaki

**Comment by sakaki-** [comment]
The new (1.4.2) release is now out, and its kernel contains built-in support for `btrfs`.
Closing now. Please re-open if you still experience issues.
Thanks,
sakaki
