### ISSUE TITLE
Install LAMP

### ISSUE THREAD

**Issue by TykeNicol** [sakaki-/gentoo-on-rpi3-64bit#92]
How to get LAMP working. Apache worked, MySql worked, PHP 7.1 worked, but not in Apache.

**Comment by sakaki-** [comment]
Apologies for not responding earlier to this, I have been (am!) swamped with the forthcoming 1.5.0 release prep.

As this is almost certainly a generic Gentoo configuration issue (if all the individual components work, and networking is live), I suggest you post an issue on the Gentoo forums [here](https://forums.gentoo.org/viewforum-f-62.html) (if not already resolved); someone there will almost certainly be able to help you.

I'll close this now but feel free to re-open if you can't get this resolved after posting there.

Thanks! sakaki
