### ISSUE TITLE
(not an error) Is the advice on placing a swap on another bus still relevant?

### ISSUE THREAD

**Issue by yrabbit** [sakaki-/gentoo-on-rpi3-64bit#94]
Do I understand correctly that the subsystem responsible for allocating memory in the swap itself uses dynamically allocated memory and therefore all my attempts to put a swap on a USB flash fail under load?

![usb-swap](https://user-images.githubusercontent.com/6075465/61834991-5afb9580-aebd-11e9-8f35-e56f71be4ce0.png)

**Comment by sakaki-** [comment]
@yrabbit, apologies for not responding to you earlier on this, been busy on the forthcoming 1.5.0 release.

Interesting point! I must say I haven't seen that particular error come up, and I run a few build servers (which at times hit the swap pretty hard) using the dual-swap setup.

If you haven't already, why not post this question on the [RPi forums](https://www.raspberrypi.org/forums/)? I'd be interested myself to see what responses the RPF/RPT engineers come back with.

Best, sakaki

**Comment by yrabbit** [comment]
I remembered what I did (compiled FreeCAD), I will try to repeat this in the near future in order to get the latest logs.
