### ISSUE TITLE
pitop v2 works great.! thanks

### ISSUE THREAD

**Issue by AkiAfroo** [sakaki-/gentoo-on-rpi3-64bit#96]
edit: i have a pitop v2 and everything works great! just wanna tell you that.

**Comment by sakaki-** [comment]
Many thanks for letting me know!

Just to double check, does shutdown work correctly to power off the PiTop hub, and does the battery monitor plugin work correctly (top right of the screen)?

Best, sakaki

**Comment by AkiAfroo** [comment]
the previous version turned off pitop v2 without problems in the latter does not turn off. i cant check it now because im doing some "Do it yourself" ("DIY") mods with the case. pi4 is out and the pitop company told that the pitop v2 will not get any upgrade like new hub etc,etc,. xD .

i will love to see an archlinux or debian derivate arm64 with all the stuff you put on. i tried 5 times gentoo and is not for me. xD thx in advance.

**Comment by sakaki-** [comment]
I plan to put out an updated version of [raspbian-nspawn-64](https://github.com/sakaki-/raspbian-nspawn-64) after the 1.5.0 Gentoo image is released, that might be of some interest (the current version should work for you on a Pi-Top too; the host userland is Raspbian Stretch, but the guest is Debian Buster).

@satmandu also has a nice Docker-based Ubuntu aarch64 image builder for the Pi4, which may be of interest if you move to that board ([here](https://github.com/satmandu/docker-rpi4-imagebuilder)).

hth, sakaki

PS I'll close this issue now, please feel free to re-open if required. S.
